#!/usr/bin/with-contenv sh

# Make sure to have a defined set of PHP binaries,
# regardless of how the package maintainer(s) named those.

rm -f /usr/bin/php
ln -s /usr/bin/php84 /usr/bin/php

rm -f /usr/sbin/php-fpm
ln -s /usr/sbin/php-fpm84 /usr/sbin/php-fpm
